# Generated by Django 5.2.4 on 2025-07-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='calificacionPromedio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cantIntercambios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fotoPerfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
