# Generated by Django 5.2.4 on 2025-07-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('ropa', 'Ropa'), ('libros', 'Libros'), ('electronica', 'Electrónica'), ('hogar', 'Hogar'), ('otros', 'Otros')], max_length=20)),
                ('imagenes', models.ImageField(upload_to='objetos/')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('intercambiado', 'Intercambiado'), ('reservado', 'Reservado')], default='disponible', max_length=20)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
