# Generated by Django 5.2.4 on 2025-07-10 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('ropa', 'Ropa'), ('libros', 'Libros'), ('electronica', 'Electrónica'), ('hogar', 'Hogar'), ('otros', 'Otros')], max_length=20)),
                ('imagen', models.ImageField(upload_to='objetos/')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('intercambiado', 'Intercambiado'), ('reservado', 'Reservado')], default='disponible', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
