# Generated by Django 5.2.4 on 2025-07-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='estadoModeracion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='objeto',
            name='motivoRechazo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
