# Generated by Django 5.2.4 on 2025-07-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_objeto_estadomoderacion_objeto_motivorechazo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objeto',
            name='estadoModeracion',
        ),
        migrations.RemoveField(
            model_name='objeto',
            name='motivoRechazo',
        ),
        migrations.AlterField(
            model_name='objeto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('disponible', 'Disponible'), ('rechazado', 'Rechazado'), ('reservado', 'Reservado'), ('intercambiado', 'Intercambiado')], default='pendiente', max_length=20),
        ),
    ]
