# Generated by Django 5.2.4 on 2025-07-14 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudIntercambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Enviada', 'Enviada'), ('Propuesta', 'Propuesta'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Completada', 'Completada')], default='Enviada', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('objetoPropuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fue_propuesto_en', to='productos.objeto')),
                ('objetoSolicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fue_solicitado_en', to='productos.objeto')),
            ],
        ),
    ]
